### ISSUE TITLE
P2. Despliegue de objetos 3D en Heroku

### ISSUE THREAD

**Issue by MaGuadalupeQuiroz** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-team-pc-box#2]
[Practica 2. Depliegue de Objeto 3D en Heroku.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-en-heroku-team-pc-box/files/8301680/Practica.2.Depliegue.de.Objeto.3D.en.Heroku.pdf)

**Comment by EDITH-R** [comment]
Calificacion: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
